import React from 'react';
import { ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-slate-100 p-6 sm:p-12 font-sans">
      <div className="max-w-3xl mx-auto space-y-8">
        <Link to="/" className="inline-flex items-center text-teal-600 hover:text-teal-700 transition-colors">
          <ArrowLeft className="w-4 h-4 mr-2" /> Back to Home
        </Link>
        <h1 className="text-3xl font-bold tracking-tight">Terms of Service</h1>
        <p className="text-sm text-slate-500">Last Updated: May 17, 2026</p>

        <div className="space-y-6 text-sm leading-relaxed text-slate-700 dark:text-slate-300">
          <section>
            <h2 className="text-xl font-semibold mb-3 text-slate-900 dark:text-slate-100">1. Nature of the Service</h2>
            <p>
              Aegis Health AI is an informational and technological tool designed strictly for tracking and organizing health records and insights. We provide automated structuring of records and insights through AI.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3 text-slate-900 dark:text-slate-100">2. Medical Disclaimer</h2>
            <p className="font-semibold p-4 bg-teal-50 dark:bg-teal-900/30 rounded-lg text-teal-900 dark:text-teal-100">
              Aegis Health AI does NOT provide medical advice, formulate final diagnoses, or replace professional clinical assessments. 
              The AI is strictly an informational tool. Always consult a qualified healthcare provider regarding diagnostic questions, 
              medication changes, or medical advice before acting on the insights generated by this application.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3 text-slate-900 dark:text-slate-100">3. User Responsibilities</h2>
            <p>
              By utilizing our services, you accept full accountability for verifying the data against your original laboratory reports or clinically issued records. You acknowledge that AI systems may occasionally misread formats or omit details, meaning it should always serve alongside, not in place of, a human doctor.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3 text-slate-900 dark:text-slate-100">4. Service Modifications</h2>
            <p>
              Aegis Health AI reserves the right to iteratively alter or pause aspects of this service to ensure platform stability or introduce regulatory updates. 
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
