import React, { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import { X, ChevronDown, ChevronUp, AlertCircle } from "lucide-react";
import { SBARSummary } from "../../types/medical";

export interface SBARPreviewProps {
  isOpen: boolean;
  onClose: () => void;
  sbar: string | null;
  isLoading?: boolean;
  error?: string | null;
}

export const SBARPreview: React.FC<SBARPreviewProps> = ({
  isOpen,
  onClose,
  sbar,
  isLoading,
  error,
}) => {
  return (
    <AnimatePresence>
      {isOpen && (
        <React.Fragment>
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/40 backdrop-blur-md z-[9900]"
            onClick={onClose}
          />
          <motion.div
            initial={{ opacity: 0, scale: 0.97 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.97 }}
            transition={{ duration: 0.3, ease: [0.16, 1, 0.3, 1] }}
            className="fixed inset-4 md:inset-auto md:top-1/2 md:left-1/2 md:-translate-x-1/2 md:-translate-y-1/2 md:w-full md:max-w-3xl bg-[var(--color-bg)] border border-[var(--color-primary)] z-[9910] rounded-[32px] shadow-2xl flex flex-col h-[90vh] md:h-[80vh] max-h-[900px]"
            role="dialog"
            aria-modal="true"
            aria-labelledby="sbar-title"
          >
            <div className="flex items-center justify-between px-6 py-5 border-b border-[var(--color-border)] shrink-0">
              <div>
                <h2
                  id="sbar-title"
                  className="text-xl font-semibold text-[var(--color-text)]"
                >
                  Clinical Handover Summary
                </h2>
                <p className="text-xs text-[var(--color-text-muted)] uppercase tracking-wider mt-1 font-medium">
                  SBAR Format (Plain Text)
                </p>
              </div>
              <button
                onClick={onClose}
                className="p-2 -mr-2 text-[var(--color-text-muted)] hover:bg-[var(--color-surface)] rounded-full transition-colors focus:outline-none"
              >
                <X size={20} />
              </button>
            </div>

            <div className="flex-1 overflow-y-auto p-6 md:p-8">
              <div className="bg-[var(--color-warning)]/10 border border-[var(--color-warning)]/20 p-4 rounded-2xl flex gap-3 mb-6">
                <AlertCircle
                  size={20}
                  className="text-[var(--color-warning)] shrink-0 mt-0.5"
                />
                <div>
                  <h4 className="text-sm font-semibold text-[var(--color-warning)] mb-0.5">
                    Professional SBAR Format
                  </h4>
                  <p className="text-sm text-[var(--color-text-muted)] leading-relaxed">
                    This summary is designed to be handed to a clinician. It is generated in plain text to ensure readability across all clinical systems and for easy printing.
                  </p>
                </div>
              </div>

              {isLoading ? (
                <div className="flex flex-col items-center justify-center py-12">
                  <div className="w-8 h-8 rounded-full border-2 border-[var(--color-primary)] border-t-transparent animate-spin mb-4" />
                  <p className="text-[var(--color-text-muted)] text-sm font-medium">
                    Synthesizing clinical data into SBAR format...
                  </p>
                </div>
              ) : error ? (
                <div className="bg-[var(--color-critical)]/10 border border-[var(--color-critical)]/20 p-6 rounded-2xl flex flex-col items-center justify-center text-center">
                  <AlertCircle
                    size={32}
                    className="text-[var(--color-critical)] mb-3"
                  />
                  <h4 className="font-semibold text-[var(--color-critical)] mb-1">
                    Error
                  </h4>
                  <p className="text-sm text-[var(--color-critical)] leading-relaxed">
                    {error}
                  </p>
                </div>
              ) : (
                <div className="bg-[var(--color-surface)]/20 p-6 rounded-24px border border-[var(--color-border)]">
                  <pre className="text-[var(--color-text)] leading-relaxed text-sm whitespace-pre-wrap font-mono">
                    {sbar || "No data provided."}
                  </pre>
                  <div className="mt-8 pt-4 border-t border-[var(--color-border)] text-center">
                    <span className="text-[var(--color-text-faint)] text-xs italic">
                      Generated by Aegis AI Clinical Engine. Not a medical diagnosis.
                    </span>
                  </div>
                </div>
              )}
            </div>

            <div className="p-6 border-t border-[var(--color-border)] bg-[var(--color-bg)] shrink-0 flex flex-col-reverse md:flex-row justify-end gap-3 rounded-b-[32px]">
              <button
                onClick={onClose}
                className="px-8 py-3 rounded-full text-sm font-medium border border-[var(--color-border)] hover:bg-[var(--color-surface)] transition-colors focus:outline-none w-full md:w-auto"
              >
                Close
              </button>
              <button
                onClick={async () => {
                  if (navigator.share) {
                    try {
                      await navigator.share({
                        title: "Clinical Handover (SBAR)",
                        text: sbar || "",
                      });
                    } catch (err) {
                      console.log("Share canceled or failed:", err);
                    }
                  } else {
                    navigator.clipboard.writeText(sbar || "");
                    alert("Summary copied to clipboard!");
                  }
                }}
                className="px-8 py-3 rounded-full text-sm font-medium bg-[var(--color-primary)] text-white hover:opacity-90 transition-opacity flex items-center justify-center gap-2 focus:outline-none w-full md:w-auto shadow-lg shadow-[var(--color-primary)]/20"
              >
                Share SBAR Report
              </button>
            </div>
          </motion.div>
        </React.Fragment>
      )}
    </AnimatePresence>
  );
};
